import Head from "next/head";
import Cta from "../components/Cta";
import Footer from "../components/Footer";
import Hero from "../components/Hero";
import MoreInfoModal from "../components/MoreInfoModal";
import Student from "../components/Student";
import Teacher from "../components/Teachers";
import Values from "../components/Values";
import localFont from '@next/font/local';

const myFont = localFont ({src: '../public/assets/font/Iran-Sans.woff',variable: '--font-inter'})


export default function Home() {
  return (
    <div dir="rtl" className={`${myFont.variable} font-sans`}>
      <Head>
        <title>Ed -Circle Education Website</title>
        <meta name="description" content="Generated by create next app" />
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:wght@200;300;400;500;600;700;800;900&display=swap"
          rel="stylesheet"
        ></link>
        <link rel="icon" href="/favicon.ico" />
        </Head>
        <h1>سلام من مهدی هستم</h1>
        <Hero/>
        <Values/>
        <Teacher/>
        <Student/>
        <MoreInfoModal/>
        <Cta/>
        <Footer/>
    </div>
  );
}
